coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 10%
        if_ci_failed: error

  ignore:
    - "tests/*"
    - "examples/*"
    - "quarto/*"
    - "docs/*"
    - "**/__pycache__/*"
    - "**/*.pyc"

comment:
  layout: "reach,diff,flags,tree,header"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - src/genjax/

github_checks:
  annotations: true
