name: Coverage Report

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    # Run coverage check daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.48.1
        locked: false

    - name: Validate codecov.yml
      run: |
        if [ -f "codecov.yml" ]; then
          echo "📋 Codecov configuration found"
          echo "✅ Configuration file present and ready for Codecov"
        else
          echo "⚠️  No codecov.yml found, using Codecov defaults"
        fi

    - name: Run comprehensive test suite
      run: pixi run test

    - name: Generate coverage report summary
      run: |
        echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        eval "$(pixi shell-hook -e test)" && coverage report --show-missing >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: genjax-coverage
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
        retention-days: 30
