name: Test Suite

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.44.0
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    
    - name: Run tests
      run: pixi run test